Changes to enable fp8 on multi devices (#149)
Summary:
- If the model is casted to bf16 (model = model.to(get_torch_dtype(dtype))), dtype = bf16 is also passed to the scale_a parameter of the float8 tensor, and caused
```
output, output_amax = torch._scaled_mm(
RuntimeError: scale_a must be float scalar
```
- The float8Linear classes used in multi-gpu are Float8Column/RowParallelLinear, sync_float8_amax_and_scale_history needs to identify these class types.

Pull Request resolved: https://github.com/pytorch-labs/float8_experimental/pull/149

Reviewed By: drisspg

Differential Revision: D51479201

Pulled By: y-sq

fbshipit-source-id: a632ade0097a46b3ce5fd70d071bab891da703b8